chore(build): add ConfigCheck workflow
mainsail-crew/MainsailOS pull request #259
Opened 2023-12-07 17:16 UTC by KwadFan

Add new check for PR or pushes,
this check inspects config files for the
bare minimum needed configuration.

This PR contains also preperation for
the new method to generate the JSON file
needed for the rpi-imager.

2024-01-08 22:02 UTC, meteyou commented on config/armbian/default
> +JSON_DESCRIPTION="A port of Armbian with preinstalled Mainsail for 3D Printer's"
```suggestion
JSON_DESCRIPTION="A port of Armbian with preinstalled Mainsail for 3D Printer's"
```
JSON_DESCRIPTION="A port of Armbian with preinstalled Mainsail for 3D printers"

2024-01-08 22:03 UTC, meteyou commented on config/orangepi/default
> +JSON_DESCRIPTION="A port of Orange Pi OS with preinstalled Mainsail for 3D Printer's"
```suggestion
JSON_DESCRIPTION="A port of Orange Pi OS with preinstalled Mainsail for 3D Printer's"
```
JSON_DESCRIPTION="A port of Orange Pi OS with preinstalled Mainsail for 3D printers"

2024-01-08 22:04 UTC, meteyou requested changes

2024-01-08 22:04 UTC, meteyou commented on config/raspberry/default
> +JSON_DESCRIPTION="A port of Raspberry Pi OS with preinstalled Mainsail for 3D Printer's"
```suggestion
JSON_DESCRIPTION="A port of Raspberry Pi OS with preinstalled Mainsail for 3D printers"
```

2024-01-12 21:16 UTC, KwadFan commented
Will not be merged, decided against it.

2024-01-12 21:16 UTC, closed without merging